version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: investor_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investor_app_dev
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investor_app
    ports:
      - "4001:4001"
    environment:
      - MIX_ENV=dev
      - PHX_HOST=0.0.0.0
      - PHX_PORT=4001
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    depends_on:
      - db
